application: log2bq
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

includes:
- mapreduce/include.yaml
